### ISSUE TITLE
unable to modify multiplexing level value 

### ISSUE THREAD

**Issue by spencer411** [comoto-pasteur-fr/DNABarcodeCompatibility_Shiny#1]
I am able to get this to work on my machine, but when I attempt to modify the multiplexing level value I am unable to do so.

**Comment by spencer411** [comment]
its actually because I did not fully install DNABarcodeCompatibility, working on updating source for modern C compiler

**Comment by etournay** [comment]
DNABarcodeCompatibility relies on the DNABarcodes dependency that is no more maintained, which causes our DNABarcodeCompatibility to be depracated in Bioconductor since a couple weeks or so. [Here](https://support.bioconductor.org/p/9156314/) is a thread on a C++ issue from the DNABarcodes package, with some hints to overcome the problem. I hope that helps in the short term. 

I would instead recommend to use DNABarcodeCompatibility from [our Shiny web server](https://dnabarcodecompatibility.pasteur.fr/app/01_DNABarcodeCompatibility) (https://dnabarcodecompatibility.pasteur.fr) from next week on (currently under maintenance)

**Comment by etournay** [comment]
[Our Shiny web server](https://dnabarcodecompatibility.pasteur.fr/app/01_DNABarcodeCompatibility) (https://dnabarcodecompatibility.pasteur.fr/) is up and running again.

**Comment by spencer411** [comment]
Thank you!

From: Raphael Etournay ***@***.***>
Date: Monday, August 26, 2024 at 8:16 AM
To: comoto-pasteur-fr/DNABarcodeCompatibility_Shiny ***@***.***>
Cc: Bruce, Spencer (HEALTH) ***@***.***>, State change ***@***.***>
Subject: Re: [comoto-pasteur-fr/DNABarcodeCompatibility_Shiny] unable to modify multiplexing level value (Issue #1)

ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.


Our Shiny web server<https://dnabarcodecompatibility.pasteur.fr/app/01_DNABarcodeCompatibility> (https://dnabarcodecompatibility.pasteur.fr/) is up and running again.
